### ISSUE TITLE
Compile failure

### ISSUE THREAD

**Issue by gravitystorm** [zerebubuth/cgimap-ruby#4]
Compiling fails, but I'm not sure if the output is misleading, since it certainly doesn't match the details in mkmf.log

```
checking for std::string() in -lstdc++... *** ../../../../ext/cgimap/extconf.rb failed ***
vs
/usr/bin/ld: cannot find -lrice
```

Full outputs below:

```
vagrant@cgimap-ruby:~/cgimap-ruby$ bundle exec rake compile
mkdir -p lib/cgimap
mkdir -p tmp/x86_64-linux/cgimap/1.9.3
cd tmp/x86_64-linux/cgimap/1.9.3
/usr/bin/ruby1.9.1 -I. ../../../../ext/cgimap/extconf.rb
checking for std::string() in -lstdc++... *** ../../../../ext/cgimap/extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=../../../../ext/cgimap
    --curdir
    --ruby=/usr/bin/ruby1.9.1
    --with-libpath
    --without-libpath
    --with-cgimap-dir
    --without-cgimap-dir
    --with-cgimap-include
    --without-cgimap-include=${cgimap-dir}/include
    --with-cgimap-lib
    --without-cgimap-lib=${cgimap-dir}/lib
    --with-stdc++lib
    --without-stdc++lib
/usr/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /usr/lib/ruby/1.9.1/mkmf.rb:461:in `try_link0'
    from /usr/lib/ruby/1.9.1/mkmf.rb:476:in `try_link'
    from /usr/lib/ruby/1.9.1/mkmf.rb:619:in `try_func'
    from /usr/lib/ruby/1.9.1/mkmf.rb:845:in `block in have_library'
    from /usr/lib/ruby/1.9.1/mkmf.rb:790:in `block in checking_for'
    from /usr/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postpone'
    from /usr/lib/ruby/1.9.1/mkmf.rb:254:in `open'
    from /usr/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
    from /usr/lib/ruby/1.9.1/mkmf.rb:254:in `open'
    from /usr/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
    from /usr/lib/ruby/1.9.1/mkmf.rb:789:in `checking_for'
    from /usr/lib/ruby/1.9.1/mkmf.rb:840:in `have_library'
    from ../../../../ext/cgimap/extconf.rb:8:in `<main>'
rake aborted!
Command failed with status (1): [/usr/bin/ruby1.9.1 -I. ../../../../ext/cgi...]
/var/lib/gems/1.9.1/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:191:in `block (2 levels) in define_compile_tasks'
/var/lib/gems/1.9.1/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:188:in `block in define_compile_tasks'
Tasks: TOP => compile => compile:x86_64-linux => compile:cgimap:x86_64-linux => copy:cgimap:x86_64-linux:1.9.3 => tmp/x86_64-linux/cgimap/1.9.3/cgimap.so => tmp/x86_64-linux/cgimap/1.9.3/Makefile
(See full trace by running task with --trace)
```

```
"g++ -o conftest -I/usr/include/ruby-1.9.1/x86_64-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I../../../../ext/cgimap -D_FORTIFY_SOURCE=2  -D_FORTIFY_SOURCE=2  -I/home/vagrant/.bundler/tmp/19134/gems/rice-1.7.0/ruby/lib/include -I/usr/include/libxml2 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -fno-strict-aliasing conftest.c  -L. -L/usr/lib -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -L/build/buildd/ruby1.9.1-1.9.3.484/debian/lib -rdynamic -Wl,-export-dynamic   -lrice     -lruby-1.9.1  -lpthread -lrt -ldl -lcrypt -lm   -lc"
/usr/bin/ld: cannot find -lrice
collect2: error: ld returned 1 exit status
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Comment by gravitystorm** [comment]
The proximate cause is there's an incorrect path stored within the rice gem when installed via bundler - see upstream report at https://github.com/jasonroelofs/rice/issues/86

**Comment by gravitystorm** [comment]
(so the workaround is to `gem install rice` before running `bundle install`, but lets see if upstream has a better suggestion!)

**Comment by pnorman** [comment]
upstream has apparently fixed this

**Comment by gravitystorm** [comment]
Confirmed fixed upstream
